/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-17 13:20:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chinh_005fsua_005fkh_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/admin/header.jsp", Long.valueOf(1610889614889L));
    _jspx_dependants.put("/WEB-INF/views/admin/footer.jsp", Long.valueOf(1610719667948L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603000256318L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1603008137689L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1511752906000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Creat An Account || Witter Multipage Responsive Template</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Start header section -->\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Quản lý chung</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- favicon\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<!--    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/favicon.ico\">-->\r\n");
      out.write("<!-- Google Fonts\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<!--    <link href=\"https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900\" rel=\"stylesheet\">-->\r\n");
      out.write("<!-- Bootstrap CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Bootstrap CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/font-awesome.min.css\">\r\n");
      out.write("<!-- admin Icon CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<!--    menu 3 vạch-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/nalika-icon.css\">\r\n");
      out.write("<!-- owl.carousel CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/owl.transitions.css\">\r\n");
      out.write("<!-- animate CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/animate.css\">\r\n");
      out.write("<!-- normalize CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/normalize.css\">\r\n");
      out.write("<!-- meanmenu icon CSS\r\n");
      out.write("    icon menu 3 vạch\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/meanmenu.min.css\">\r\n");
      out.write("<!-- main CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/main.css\">\r\n");
      out.write("<!-- morrisjs CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/morrisjs/morris.css\">\r\n");
      out.write("<!-- mCustomScrollbar CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/scrollbar/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("<!-- metisMenu CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/metisMenu/metisMenu.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/metisMenu/metisMenu-vertical.css\">\r\n");
      out.write("<!-- calendar CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/calendar/fullcalendar.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/calendar/fullcalendar.print.min.css\">\r\n");
      out.write("<!-- style CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/style.css\">\r\n");
      out.write("<!-- responsive CSS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/Content/css/responsive.css\">\r\n");
      out.write("<!-- modernizr JS\r\n");
      out.write("    ============================================ -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"left-sidebar-pro\">\r\n");
      out.write("\t\t<nav id=\"sidebar\" class=\"\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-header\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/admin\"> <img\r\n");
      out.write("\t\t\t\t\tclass=\"main-logo\" style=\"width: 200px\" src=\"\" alt=\"\" />\r\n");
      out.write("\t\t\t\t</a> <strong> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/img/logo/logosn.png\"\r\n");
      out.write("\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t</strong>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"nalika-profile\">\r\n");
      out.write("\t\t\t\t<div class=\"profile-dtl\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"min-dtn\"></span>\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"profile-social-dtl\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"dtl-social\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"icon nalika-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"icon nalika-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"icon nalika-linkedin\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"left-custom-menu-adp-wrap comment-scrollbar\">\r\n");
      out.write("\t\t\t\t<nav class=\"sidebar-nav left-sidebar-menu-pro\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"metismenu\" id=\"menu1\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a class=\"has-arrow\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/admin/listProduct\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon nalika-home icon-wrap\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mini-click-non\">Quản lý sản phẩm</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu-angle\" aria-expanded=\"true\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Quản lý sản phẩm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/admin/listProduct\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"mini-sub-pro\">Quản lý sản phẩm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Quản lý khách hàng\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/admin/listCustomer\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"mini-sub-pro\">Quản lý khách hàng</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Quản lý loại sản phẩm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/admin/listProductType\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"mini-sub-pro\">Quản lý loại sản phẩm</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Quản lý đơn hàng\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/admin/listOrder\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"mini-sub-pro\">Quản lý đơn hàng</span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"removable\"><a class=\"has-arrow\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon admin-new-file icon-wrap\"></i> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon nalika-pie-chart icon-wrap\"> </i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mini-click-non\">Pages</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"submenu-angle\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Đăng ký\" href=\"\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"mini-sub-pro\">Đăng ký</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Lock\" href=\"\"> <span class=\"mini-sub-pro\">Lock</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a title=\"Password Recovery\" href=\"\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"mini-sub-pro\">Password Recovery</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container body-content\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo-pro\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"admin\"> <img class=\"main-logo\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/img/logo/logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"header-advance-area\">\r\n");
      out.write("\t\t\t<div class=\"header-top-area\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"header-top-wraper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-1 col-md-0 col-sm-1 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"menu-switcher-pro\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"sidebarCollapse\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn bar-button-pro header-drl-controller-btn btn-info navbar-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-menu-task\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-7 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"header-top-menu tabl-d-n hd-search-rp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"breadcome-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<form role=\"search\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Search...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\"> <a href=\"\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-5 col-md-5 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"header-right-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"nav navbar-nav mai-top-nav header-right-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-mail\" aria-hidden=\"true\"> </i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"indicator-ms\"> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div role=\"menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"author-message-top dropdown-menu animated zoomIn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-single-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h1>Tin nhắn</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"message-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/img/contact/1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"message-date\">16 tháng 9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Vân Anh</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Mau chóng hoàn thành đồ án nhé.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/img/contact/4.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"message-date\">16 tháng 9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>anh Hoàng</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Hoàn thành sớm công việc giúp anh.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/img/contact/3.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"message-date\">16 tháng 9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Giám đốc</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Em lên văn phòng gặp anh xíu nhé.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/img/contact/2.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"message-date\">16 tháng 9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Quyên</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Họp trưởng phòng lúc 10h.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"message-view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Hiển thị tất cả tin nhắn</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trole=\"button\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-alarm\" aria-hidden=\"true\"> </i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"indicator-nt\"> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div role=\"menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"notification-author dropdown-menu animated zoomIn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-single-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h1>Thông báo</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<ul class=\"notification-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-tick\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-date\">16 tháng 9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Trang Phạm</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Trang Phạm vừa bình luận sản phẩm.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-cloud\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-date\">16 tháng 9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Hoài Tú</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Hoài Tú vừa gửi một tin nhắn.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-folder\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-date\">15 tháng 10</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Davi</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Davi vừa gửi một tin nhắn.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-bar-chart\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-date\">14 tháng 10</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Hoài Tú</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Hoài Tú vừa gửi một tin nhắn.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-view\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Hiển thị tất cả</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<ul role=\"menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-header-top author-log dropdown-menu animated zoomIn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-home author-log-ic\"> </span> Đăng kí\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-user author-log-ic\"></span> Hồ sơ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-settings author-log-ic\"> </span> Cài\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tđặt\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-unlocked author-log-ic\"> </span> Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\txuất\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</ul> <a href=\"#\" data-toggle=\"dropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-expanded=\"false\" class=\"nav-link dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-user\"></i> <span class=\"admin-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</span> <i class=\"icon nalika-down-arrow nalika-angle-dw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Mobile Menu end -->\r\n");
      out.write("\t\t\t<div class=\" all-content-wrapper breadcome-area\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"breadcome-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"breadcomb-wp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"breadcomb-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon nalika-home\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"breadcomb-ctn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h2>Pate-ER FOOD</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tChào mừng Pate-ER <span class=\"bread-ntd\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-6\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t<!-- / header section -->\n");
      out.write("\n");
      out.write("\t<div class=\"all-content-wrapper\">\n");
      out.write("\t\t<!-- Single pro tab start-->\n");
      out.write("\t\t<div class=\"single-product-tab-area mg-b-30\">\n");
      out.write("\t\t\t<!-- Single pro tab review Start-->\n");
      out.write("\t\t\t<div class=\"single-pro-review-area\">\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"review-tab-pro-inner\">\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"myTab3\" class=\"tab-review-design\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#description\"> <i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"icon nalika-edit\" aria-hidden=\"true\"> </i> Chỉnh sửa\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tngười dùng\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myTabContent\" class=\"tab-content custom-product-edit\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"product-tab-list tab-pane fade active in\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"description\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<form method=\"post\" modelAttribute=\"user\" action=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"idUser\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.idUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t* Username: <input name=\"email\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <br /> *\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tĐịa chỉ Email: <input name=\"username\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t* Mật khẩu: <input type=\"password\" name=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t* Nhập lại mật khẩu: <input type=\"password\" name=\"request\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.request }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tGiới tính: <select name=\"gender\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Nam\">Nam</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Nữ\">Nu</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Khác\">Khac</option>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select> <br /> * Ngày sinh: <input name=\"dateOfBirth\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.dateOfBirth }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t* Số điện thoại: <input name=\"phone\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" /> <br /> * Địa chỉ:\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"address\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"text-center custom-pro-edt-ds\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-ctl-bt waves-effect waves-light\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLƯU</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-ctl-bt waves-effect waves-light\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tHỦY</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!--FOOTER -->\n");
      out.write("\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer class=\"all-content-wrapper\">\r\n");
      out.write("\t\t<div class=\"footer-copyright-area\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-copy-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tCopyright © 2018 <a href=\"https://colorlib.com/wp/templates/\">Colorlib</a>\r\n");
      out.write("\t\t\t\t\t\t\t\tAll rights reserved.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- jquery\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<!-- bootstrap JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- wow JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/wow.min.js\"></script>\r\n");
      out.write("\t<!-- price-slider JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/jquery-price-slider.js\"></script>\r\n");
      out.write("\t<!-- meanmenu JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/jquery.meanmenu.js\"></script>\r\n");
      out.write("\t<!-- owl.carousel JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- sticky JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/jquery.sticky.js\"></script>\r\n");
      out.write("\t<!-- scrollUp JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("\t<!-- mCustomScrollbar JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/scrollbar/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/scrollbar/mCustomScrollbar-active.js\"></script>\r\n");
      out.write("\t<!-- metisMenu JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/metisMenu/metisMenu-active.js\"></script>\r\n");
      out.write("\t<!-- morrisjs JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/sparkline/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/sparkline/jquery.charts-sparkline.js\"></script>\r\n");
      out.write("\t<!-- calendar JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/calendar/moment.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/calendar/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/calendar/fullcalendar-active.js\"></script>\r\n");
      out.write("\t<!-- plugins JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/plugins.js\"></script>\r\n");
      out.write("\t<!-- main JS\r\n");
      out.write("============================================ -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/Content/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- END FOOTER -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
