/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-12-27 06:13:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URI;

public final class single_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1609048705565L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1608435030255L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603000256318L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URI");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Product Details || Witter Multipage Responsive Template</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Start header section -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<!-- favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:400,700,600,500,300\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- all css here -->\r\n");
      out.write("<!-- bootstrap v3.3.6 css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/bootstrap.min.css\" />\r\n");
      out.write("<!-- animate css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/animate.css\" />\r\n");
      out.write("<!-- jquery-ui.min css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/jquery-ui.min.css\" />\r\n");
      out.write("<!-- meanmenu css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/meanmenu.min.css\" />\r\n");
      out.write("<!-- Font-Awesome css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.12.0/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("<!-- pe-icon-7-stroke css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/pe-icon-7-stroke.css\" />\r\n");
      out.write("<!-- Flaticon css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/flaticon.css\" />\r\n");
      out.write("<!-- venobox css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/venobox/venobox.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<!-- nivo slider css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/css/nivo-slider.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/css/preview.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<!-- owl.carousel css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/owl.carousel.css\" />\r\n");
      out.write("<!-- style css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/style.css\" />\r\n");
      out.write("<!-- responsive css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/responsive.css\" />\r\n");
      out.write("<!-- modernizr css -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Add your site or application content here -->\r\n");
      out.write("\t<!--Header Area Start-->\r\n");
      out.write("\t<div class=\"header-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row header-header\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-6 col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/BookStore\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1 col-sm-6 visible-sm col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"user-login\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-people\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a href=\"signup\">Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tkí</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a href=\"login\">Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnhập</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shoping-cart\"><a href=\"shopping_cart\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-shop\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 col-sm-12 hidden-xs\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mainmenu text-center\">\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"shop\">Sách</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"shop\">Khuyến mãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#footer\">Liên Hệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"user-login\"><a> <i class=\"flaticon-people\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a href=\"signup\">Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tkí</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a href=\"login\">Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnhập</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shoping-cart\"><a href=\"shopping_cart\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-shop\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--Header Area End-->\r\n");
      out.write("\t<!-- Mobile Menu Start -->\r\n");
      out.write("\t<div class=\"mobile-menu-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mobile-menu\">\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"shop\">Sách</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"shop\">Khuyến mãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#footer\">Liên Hệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Mobile Menu End -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<!-- / header section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Breadcrumbs Area Start -->\r\n");
      out.write("\t<div class=\"breadcrumbs-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Chi tiết sản phẩm</h2>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"breadcrumbs-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a title=\"Return to Home\" href=\"index.html\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchủ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Chi tiết sản phẩm</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Breadcrumbs Area Start -->\r\n");
      out.write("\t<!-- Single Product Area Start -->\r\n");
      out.write("\t<div class=\"single-product-area section-padding\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /WEB-INF/views/single-product.jsp(38,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/single-product.jsp(38,3) '${Productdetail }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Productdetail }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/views/single-product.jsp(38,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("books");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t<div class=\"row\">\r\n");
              out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-7\">\r\n");
              out.write("\t\t\t\t\t\t<div class=\"single-product-image-inner\">\r\n");
              out.write("\t\t\t\t\t\t\t<!-- Tab panes -->\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"tab-content\">\r\n");
              out.write("\t\t\t\t\t\t\t\t");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"one\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 90%; margin-bottom: 30px; position: relative;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a class=\"venobox\" href=\"\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tdata-gall=\"gallery\" title=\"\"> <img\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
              out.print(request.getContextPath());
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.hinhAnh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" alt=\"\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
              out.print(request.getContextPath());
              out.write("/assets/img/sale.png\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\talt=\"\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<p\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 20px; position: absolute; left: 50%; top: 55%; transform: translate(-50%, -50%); color: white;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t30%</p>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"two\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a class=\"venobox\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
              out.print(request.getContextPath());
              out.write("/img/single-product/bg-2.jpg\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tdata-gall=\"gallery\" title=\"\"> <img\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
              out.print(request.getContextPath());
              out.write("/assets/img/shop/tt12.jpg\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\talt=\"\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"three\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a class=\"venobox\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
              out.print(request.getContextPath());
              out.write("/img/single-product/bg-3.jpg\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tdata-gall=\"gallery\" title=\"\"> <img\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
              out.print(request.getContextPath());
              out.write("/assets/img/shop/tt12.jpg\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\talt=\"\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<!-- Nav tabs -->\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-5\">\r\n");
              out.write("\t\t\t\t\t\t<div class=\"single-product-details\">\r\n");
              out.write("\t\t\t\t\t\t\t<h2>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.tenSach}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</h2>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"single-product-price\">\r\n");
              out.write("\t\t\t\t\t\t\t\t");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t<h2>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.gia }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(".000VND</h2>\r\n");
              out.write("\t\t\t\t\t\t\t\t<span style=\"color: black; font-size: 18px;\" class=\"old-price\">500.000đ</span>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<form action=\"\" method=\"get\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<input style=\"visibility: hidden;\" name=\"maSach\" type=\"text\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\tvalue=\"1\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"product-attributes clearfix\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<span class=\"pull-left\" id=\"quantity-wanted-p\"> <span\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tclass=\"dec qtybutton\">-</span> <input id=\"soLuongMua\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"soLuongMua\" value=\"1\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tclass=\"cart-plus-minus-box\" /> <span class=\"inc qtybutton\">+</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</span> <span> <input type=\"submit\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tclass=\"cart-btn btn-default\" value=\"Thêm vào giỏ hàng\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</form>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"add-to-wishlist\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<a class=\"wish-btn\" href=\"#\"> <i class=\"far fa-heart\"></i>\r\n");
              out.write("\t\t\t\t\t\t\t\t\tThêm vào danh sách yêu thích\r\n");
              out.write("\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-details-tab-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"p-details-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"p-details-nav-tab\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#more-info\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"more-info\" role=\"tab\" data-toggle=\"tab\">Giới\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tthiệu sản phẩm</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"#data\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"data\" role=\"tab\" data-toggle=\"tab\">Thông tin\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsản phẩm</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li role=\"presentation\"><a href=\"#reviews\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"reviews\" role=\"tab\" data-toggle=\"tab\">Bình\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tluận sản phẩm</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content review\">\r\n");
      out.write("\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"more-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table-data-sheet\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"odd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Tên</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.tenSach}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"even\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Thể loại</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.theloaisach }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"odd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Tên tác giả</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.tenTacGia }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"reviews\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"product-comments-block-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"comment-here\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-comment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-ninja\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form name=\"commentArea\" class=\"AreaComment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label style=\"display: block;\">NoName</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"Thêm bình luận ....\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"commentText\" /> <input type=\"button\" value=\"Đăng\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"comment()\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"CommentArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-here\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"box-shadow: 0 1px 5px rgba(0, 0, 0, 0.15); padding: 10px 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user-comment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-ninja\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"AreaComment\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: flex; flex-direction: column;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"margin: 0px; font-weight: 600;\">NoName</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>No commnent</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Single Product Area End -->\r\n");
      out.write("\t<!-- Related Product Area Start -->\r\n");
      out.write("\t<div class=\"related-product-area\">\r\n");
      out.write("\t\t<h2 class=\"section-title\">Sản phẩm tương tự</h2>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"related-product indicator-style\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-banner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"single-banner-image-wrapper\"> <img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/shop/tt20.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"functional-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a title=\"Thêm vào giỏ hàng\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Add to Wishlist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"far fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Xem nhanh\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-compress-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"img/sale.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; position: absolute; left: 15%; top: 55%; transform: translate(0, -50%); color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t30%</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Book Name </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3;\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t250.000đ <span style=\"color: black;\" class=\"old-price\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"singleProductController?idProduct=\"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlistSach.get(i).getGia()%>.000<span>đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-banner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"single-banner-image-wrapper\"> <img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/shop/tt20.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"functional-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a title=\"Thêm vào giỏ hàng\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Add to Wishlist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"far fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Xem nhanh\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-compress-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"img/sale.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; position: absolute; left: 15%; top: 55%; transform: translate(0, -50%); color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t30%</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Book Name </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3;\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t250.000đ <span style=\"color: black;\" class=\"old-price\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlistSach.get(i).getGia()%>.000<span>đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-banner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"single-banner-image-wrapper\"> <img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/shop/tt20.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"functional-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a title=\"Thêm vào giỏ hàng\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Add to Wishlist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"far fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Xem nhanh\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-compress-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"img/sale.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; position: absolute; left: 15%; top: 55%; transform: translate(0, -50%); color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t30%</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Book Name </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3;\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t250.000đ <span style=\"color: black;\" class=\"old-price\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlistSach.get(i).getGia()%>.000<span>đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-banner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"single-banner-image-wrapper\"> <img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/shop/tt20.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"functional-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a title=\"Thêm vào giỏ hàng\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Add to Wishlist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"far fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Xem nhanh\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-compress-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"img/sale.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; position: absolute; left: 15%; top: 55%; transform: translate(0, -50%); color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t30%</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Book Name </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3;\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t250.000đ <span style=\"color: black;\" class=\"old-price\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlistSach.get(i).getGia()%>.000<span>đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-banner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"single-banner-image-wrapper\"> <img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/shop/tt20.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"product-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"functional-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a title=\"Thêm vào giỏ hàng\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Add to Wishlist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"far fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Xem nhanh\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal1\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-compress-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"img/sale.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; position: absolute; left: 15%; top: 55%; transform: translate(0, -50%); color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t30%</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Book Name </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3;\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t250.000đ <span style=\"color: black;\" class=\"old-price\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"singleProductController?idProduct=\">listSach.get(i).getTenSach()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3\" class=\"price-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlistSach.get(i).getGia()%>.000<span>đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Related Product Area End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--FOOTER -->\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Footer Area Start -->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-top-area\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo-2.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Sứ mệnh của chúng tôi là mang đến cho khách hàng tận hưởng\r\n");
      out.write("\t\t\t\t\t\t\t\tcác dịch vụ chất lượng và nhận được những cuốn sách tốt nhất.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-location\"></i> Q.Thủ Đức, Tp.Hồ Chí\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMinh</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-technology\"></i> (+800) 123 4567 890\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-web\"></i> info@bookstore.com</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">VỀ WRITER</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"about.jsp\">Giới thiệu Writer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Thông tin giao hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Điều khoản sử dụng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Hướng dẫn mua hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">TÀI KHOẢN</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"my-account.jsp\">Tài khoản của tôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"login.jsp\">Đăng nhập</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"cart.jsp\">Giỏ hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"wishlist.jsp\">Theo dõi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"checkout.jsp\">Thanh toán</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">CỬA HÀNG</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách đổi trả hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chương trình thành viên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách mua sĩ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chi nhánh</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Tuyển dụng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer footer-newsletter\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">BẢN TIN WITTER</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hàng ngàn sản phẩm và chương trình khuyến mãi siêu hấp dẫn\r\n");
      out.write("\t\t\t\t\t\t\t\tđang chờ bạn.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Địa chỉ email của bạn ...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-search btn-small\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tĐĂNG KÍ</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"flaticon-networking\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-social\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-social-1\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-social-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-video\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4 visible-sm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">CỬA HÀNG</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách đổi trả hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chương trình thành viên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách mua sĩ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chi nhánh</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Tuyển dụng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-bottom\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bottom-left pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tCopyright &copy; 2016 <span><a href=\"#\">DevItems</a></span>. All\r\n");
      out.write("\t\t\t\t\t\t\t\tRight Reserved.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bottom-right pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/paypal.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- Footer Area End -->\r\n");
      out.write("\r\n");
      out.write("\t<!--Quickview Product Start -->\r\n");
      out.write("\t<div id=\"quickview-wrapper\">\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"productModal1\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-product\" style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-images\" style=\"width: 60%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"main-image images\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/shop/tn2.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1 style=\"font-size: 22px;\">Book Name</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"price-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"s-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"special-price\"> <span class=\"amount\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 25px;\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"see-all\">Xem chi tiết</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"quick-add-to-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display: flex; justify-content: center; align-items: center;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"single_add_to_cart_button\" href=\"#\">Mua Ngay</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"height: 300px; overflow-y: scroll;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"quick-desc\">Hay cực</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- .product-info -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--End of Quickview Product-->\r\n");
      out.write("\t<!-- all js here -->\r\n");
      out.write("\t<!-- jquery latest version -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("\t<!-- bootstrap js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- owl.carousel js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- jquery-ui js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- jquery Counterup js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- jquery countdown js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("\t<!-- jquery countdown js -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/venobox/venobox.min.js\"></script>\r\n");
      out.write("\t<!-- jquery Meanmenu js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.meanmenu.js\"></script>\r\n");
      out.write("\t<!-- wow js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/wow.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tnew WOW().init();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- scrollUp JS -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("\t<!-- plugins js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/plugins.js\"></script>\r\n");
      out.write("\t<!-- Nivo slider js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/js/jquery.nivo.slider.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/home.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<!-- main js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- END FOOTER -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/single-product.jsp(134,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/single-product.jsp(134,8) '${Productdetail }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Productdetail }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/single-product.jsp(134,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("books");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.moTa }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
