/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-16 14:37:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URI;

public final class Languagle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603000256318L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/views/home/header.jsp", Long.valueOf(1610734976360L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URI");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\ttop: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".skiptranslate {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#google_translate_element2 {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write("/*  */\r\n");
      out.write(".pagination {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 8px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttransition: background-color .3s;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a.active {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: 1px solid #4CAF50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a:hover:not(.active) {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start header section -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<!-- favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:400,700,600,500,300\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- all css here -->\r\n");
      out.write("<!-- bootstrap v3.3.6 css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/bootstrap.min.css\" />\r\n");
      out.write("<!-- animate css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/animate.css\" />\r\n");
      out.write("<!-- jquery-ui.min css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/jquery-ui.min.css\" />\r\n");
      out.write("<!-- meanmenu css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/meanmenu.min.css\" />\r\n");
      out.write("<!-- Font-Awesome css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.12.0/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("<!-- pe-icon-7-stroke css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/pe-icon-7-stroke.css\" />\r\n");
      out.write("<!-- Flaticon css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/flaticon.css\" />\r\n");
      out.write("<!-- venobox css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/venobox/venobox.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<!-- nivo slider css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/css/nivo-slider.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/css/preview.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<!-- owl.carousel css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/owl.carousel.css\" />\r\n");
      out.write("<!-- style css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/style.css\" />\r\n");
      out.write("<!-- responsive css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/responsive.css\" />\r\n");
      out.write("<!-- modernizr css -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Thêm phần ngôn ngữ  -->\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\ttop: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".skiptranslate {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#google_translate_element2 {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!--  -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Add your site or application content here -->\r\n");
      out.write("\t<!--Header Area Start-->\r\n");
      out.write("\t<div class=\"header-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row header-header\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-6 col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1 col-sm-6 visible-sm col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"user-login\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-people\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-user\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/home/header.jsp(111,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username ==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a href=\"signup\">Đăng\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tkí</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/login\">Đăng nhập</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/views/home/header.jsp(125,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username !=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<p style=\"color: red; padding-left: 15px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"my_account?email=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Thông\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttin tài khoản</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/logout\">Đăng xuất</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shoping-cart\"><a href=\"shopping_cart\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-shop\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-sm-12 hidden-xs\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mainmenu text-center\">\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\">Sách</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/sale\">Khuyến\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin\">Liên\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tHệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t\t<!--  Viết tạo div để đổi ngôn ngữ :    -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"google_translate_element2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"skiptranslate goog-te-gadget\" dir=\"ltr\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\":0.targetLanguage\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"goog-te-combo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Tiện ích con dịch ngôn ngữ\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"\">Chọn Ngôn ngữ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\tĐược hỗ trợ bởi <span style=\"white-space: nowrap\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"goog-logo-link\" href=\"https://translate.google.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_blank\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_42x16dp.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"37px\" height=\"14px\" style=\"padding-right: 3px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Google Dịch\">Dịch</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-item\" style=\"display: flex; position: absolute;\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\" title=\"VI\" class=\"lang-vi first\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"doGTranslate('vi|vi');return false;\" hreflang=\"vi\"\r\n");
      out.write("\t\t\t\t\t\t\tlang=\"vi\" role=\"menuitem\">VI <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/vn.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"#\" title=\"EN\" class=\"lang-en last\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"doGTranslate('vi|en');return false;\" hreflang=\"en\"\r\n");
      out.write("\t\t\t\t\t\t\tlang=\"en\" role=\"menuitem\"> EN <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/usa.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"user-login\"><a> <i class=\"flaticon-people\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f2_reused = false;
      try {
        _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f2.setParent(null);
        // /WEB-INF/views/home/header.jsp(204,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username ==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
        if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/signup\">Đăng kí</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/login\">Đăng nhập</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        _jspx_th_c_005fif_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f3_reused = false;
      try {
        _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f3.setParent(null);
        // /WEB-INF/views/home/header.jsp(218,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username !=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
        if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<p style=\"color: red\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/my_account?email=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Thông\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttin tài khoản</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/logout\">Đăng xuất</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
        _jspx_th_c_005fif_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shoping-cart\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/shopping_cart\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-shop\"><span style=\"color: white-space:;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--Header Area End-->\r\n");
      out.write("\t<!-- Mobile Menu Start -->\r\n");
      out.write("\t<div class=\"mobile-menu-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mobile-menu\">\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\">Sách</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\">Khuyến\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin\">Liên\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tHệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Mobile Menu End -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Xử lý ngôn ngữ -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction googleTranslateElementInit2() {\r\n");
      out.write("\t\t\tnew google.translate.TranslateElement({\r\n");
      out.write("\t\t\t\tpageLanguage : 'vi',\r\n");
      out.write("\t\t\t\tautoDisplay : false\r\n");
      out.write("\t\t\t}, 'google_translate_element2');\r\n");
      out.write("\t\t\tvar removePopup = document.getElementById('goog-gt-tt');\r\n");
      out.write("\t\t\tremovePopup.parentNode.removeChild(removePopup);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction GTranslateFireEvent(element, event) {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tif (document.createEventObject) {\r\n");
      out.write("\t\t\t\t\tvar evt = document.createEventObject();\r\n");
      out.write("\t\t\t\t\telement.fireEvent('on' + event, evt)\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar evt = document.createEvent('HTMLEvents');\r\n");
      out.write("\t\t\t\t\tevt.initEvent(event, true, true);\r\n");
      out.write("\t\t\t\t\telement.dispatchEvent(evt)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction doGTranslate(lang_pair) {\r\n");
      out.write("\t\t\tif (lang_pair.value)\r\n");
      out.write("\t\t\t\tlang_pair = lang_pair.value;\r\n");
      out.write("\t\t\tif (lang_pair == '')\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tvar lang = lang_pair.split('|')[1];\r\n");
      out.write("\t\t\tvar teCombo;\r\n");
      out.write("\t\t\tvar sel = document.getElementsByTagName('select');\r\n");
      out.write("\t\t\tfor (var i = 0; sel.length > i; i++) {\r\n");
      out.write("\t\t\t\tif (sel[i].className == 'goog-te-combo')\r\n");
      out.write("\t\t\t\t\tteCombo = sel[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.getElementById('google_translate_element2') == null\r\n");
      out.write("\t\t\t\t\t|| document.getElementById('google_translate_element2').innerHTML.length == 0\r\n");
      out.write("\t\t\t\t\t|| teCombo.length == 0 || teCombo.innerHTML.length == 0) {\r\n");
      out.write("\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\tdoGTranslate(lang_pair)\r\n");
      out.write("\t\t\t\t}, 500)\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tteCombo.value = lang;\r\n");
      out.write("\t\t\t\tGTranslateFireEvent(teCombo, 'change');\r\n");
      out.write("\t\t\t\tGTranslateFireEvent(teCombo, 'change')\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<!-- / header section -->\r\n");
      out.write("\r\n");
      out.write("\t<h1>Trang ngôn gnuwx</h1>\r\n");
      out.write("\t<div id=\"google_translate_element2\">\r\n");
      out.write("\t\t<div class=\"skiptranslate goog-te-gadget\" dir=\"ltr\" style=\"\">\r\n");
      out.write("\t\t\t<div id=\":0.targetLanguage\">\r\n");
      out.write("\t\t\t\t<select class=\"goog-te-combo\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Tiện ích con dịch ngôn ngữ\"><option value=\"\">Chọn\r\n");
      out.write("\t\t\t\t\t\tNgôn ngữ</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\tĐược hỗ trợ bởi <span style=\"white-space: nowrap\"><a\r\n");
      out.write("\t\t\t\tclass=\"goog-logo-link\" href=\"https://translate.google.com\"\r\n");
      out.write("\t\t\t\ttarget=\"_blank\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"https://www.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_42x16dp.png\"\r\n");
      out.write("\t\t\t\t\twidth=\"37px\" height=\"14px\" style=\"padding-right: 3px\"\r\n");
      out.write("\t\t\t\t\talt=\"Google Dịch\">Dịch</a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<li class=\"menu-item\"><a href=\"#\" title=\"VI\" class=\"lang-vi first\"\r\n");
      out.write("\t\tonclick=\"doGTranslate('vi|vi');return false;\" hreflang=\"vi\" lang=\"vi\"\r\n");
      out.write("\t\trole=\"menuitem\">VI <!-- <img src=\"{{ asset('uploads/icon/flag_vi.gif') }}\"\r\n");
      out.write("\t\t\talt=\"\" class=\"img-fluid\"> --> <img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/vn.png\" alt=\"\"\r\n");
      out.write("\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</a> <a href=\"#\" title=\"EN\" class=\"lang-en last\"\r\n");
      out.write("\t\tonclick=\"doGTranslate('vi|en');return false;\" hreflang=\"en\" lang=\"en\"\r\n");
      out.write("\t\trole=\"menuitem\"> EN <!-- <img\r\n");
      out.write("\t\t\tsrc=\"{{ asset('uploads/icon/flag_en.gif') }}\" alt=\"\"\r\n");
      out.write("\t\t\tclass=\"img-fluid\"> --> <img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/usa.png\" alt=\"\"\r\n");
      out.write("\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h1>Hôm nay em đi học.</h1>\r\n");
      out.write("\t\t\t<h3>Thức dậy lúc 6AM</h3>\r\n");
      out.write("\t\t\t<h5>Chào tú tôi đứng đay từ chiều</h5>\r\n");
      out.write("\r\n");
      out.write("\t</a></li>\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /WEB-INF/views/home/Languagle.jsp(95,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home/Languagle.jsp(95,3) '${listSach }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listSach }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /WEB-INF/views/home/Languagle.jsp(95,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("books");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t<div class=\"shop-single-product-area\">\r\n");
              out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-6\">\r\n");
              out.write("\t\t\t\t\t\t<div class=\"single-banner\">\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"product-wrapper\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<a href=\"single_product?maSach=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.maSach }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\tclass=\"single-banner-image-wrapper\"> <img alt=\"\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
              out.print(request.getContextPath());
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.hinhAnh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"product-description\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"functional-buttons\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<a title=\"Thêm vào giỏ hàng\" href=\"shopping_cart\"> <i\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-shopping-cart\"></i>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"wishlist\" title=\"Thêm vào danh sách yêu thích\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"far fa-heart\"></i>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" title=\"Xem nhanh\" data-toggle=\"modal\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\tdata-target=\"#productModal1\"> <i\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-compress-alt\"></i>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div\r\n");
              out.write("\t\t\t\t\t\t\t\tstyle=\"width: 15%; z-index: 999; position: absolute; top: 0; right: 0;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<img src=\"");
              out.print(request.getContextPath());
              out.write("/assets/img/sale.png\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\talt=\"\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t<p\r\n");
              out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; position: absolute; left: 15%; top: 55%; transform: translate(0, -50%); color: white;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.khuyenMai }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("%</p>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"banner-bottom text-center\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"banner-bottom-title\" style=\"height: 40px\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a href=\"\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.tenSach}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(" </a>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div style=\"color: #32b5f3\" class=\"price-2\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${books.gia }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(".000 VND <span style=\"color: black;\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tclass=\"old-price\">500.000đ</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>&nbsp</div>\r\n");
      out.write("\t\t<!-- Phân trang -->\r\n");
      out.write("\t\t<div class=\"pagination\">\r\n");
      out.write("\t\t\t<h3>Total item : [[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalItems }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]]</h3>\r\n");
      out.write("\t\t\t<h2>Page [[ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ]] of [[ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ]]</h2>\r\n");
      out.write("\t\t\t&nbsp ; <a if=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage >1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/lang/1\">First</a>\r\n");
      out.write("\t\t\t<!--  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a if=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage >1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/lang/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage -1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Previous</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t-----&nbsp;\r\n");
      out.write("\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f1_reused = false;
      try {
        _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f1.setParent(null);
        // /WEB-INF/views/home/Languagle.jsp(159,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f1.setVar("loop");
        // /WEB-INF/views/home/Languagle.jsp(159,3) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f1.setBegin(1);
        // /WEB-INF/views/home/Languagle.jsp(159,3) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPage}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
        int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
          if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t<span> <a href=\"");
              out.print(request.getContextPath());
              out.write("/lang/");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t</span>\r\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f1.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
        _jspx_th_c_005fforEach_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a if=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage < totalPage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/lang/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage +1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Next</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a if=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage < totalPage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/lang/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Last</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--  -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/home/header.jsp(239,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.myCartNum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/home/Languagle.jsp(161,6) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
