/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-17 17:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URI;

public final class success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/home/footer.jsp", Long.valueOf(1610719668953L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603000256318L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/CDWEB_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/views/home/header.jsp", Long.valueOf(1610887315754L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URI");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Shop || Witter Multipage Responsive Template</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/JavaScript-autoComplete/1.0.4/auto-complete.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Start header section -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<!-- favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:400,700,600,500,300\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- all css here -->\r\n");
      out.write("<!-- bootstrap v3.3.6 css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/bootstrap.min.css\" />\r\n");
      out.write("<!-- animate css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/animate.css\" />\r\n");
      out.write("<!-- jquery-ui.min css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/jquery-ui.min.css\" />\r\n");
      out.write("<!-- meanmenu css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/meanmenu.min.css\" />\r\n");
      out.write("<!-- Font-Awesome css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.12.0/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("<!-- pe-icon-7-stroke css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/pe-icon-7-stroke.css\" />\r\n");
      out.write("<!-- Flaticon css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/flaticon.css\" />\r\n");
      out.write("<!-- venobox css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/venobox/venobox.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<!-- nivo slider css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/css/nivo-slider.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/css/preview.css\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<!-- owl.carousel css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/owl.carousel.css\" />\r\n");
      out.write("<!-- style css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/style.css\" />\r\n");
      out.write("<!-- responsive css -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/responsive.css\" />\r\n");
      out.write("<!-- modernizr css -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/modernizr-2.8.3.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Thêm phần ngôn ngữ  -->\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\ttop: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".skiptranslate {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#google_translate_element2 {\r\n");
      out.write("\tdisplay: none\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!--  -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Add your site or application content here -->\r\n");
      out.write("\t<!--Header Area Start-->\r\n");
      out.write("\t<div class=\"header-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row header-header\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-6 col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-1 col-sm-6 visible-sm col-xs-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"user-login\"><a href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-people\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-user\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/home/header.jsp(111,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name ==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a href=\"signup\">Đăng\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tkí</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/login\">Đăng nhập</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/views/home/header.jsp(125,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<p style=\"color: red; padding-left: 15px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"my_account?email=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Thông\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttin tài khoản</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f2_reused = false;
            try {
              _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
              // /WEB-INF/views/home/header.jsp(133,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.level == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
              if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/admin\">Admin</a>\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
              _jspx_th_c_005fif_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/j_spring_security_logout\">Đăng\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\txuất</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shoping-cart\"><a href=\"shopping_cart\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-shop\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-sm-12 hidden-xs\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mainmenu text-center\">\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\">Sách</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/sale\">Khuyến\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Liên Hệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t\t<!--  Viết tạo div để đổi ngôn ngữ :    -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"google_translate_element2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"skiptranslate goog-te-gadget\" dir=\"ltr\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\":0.targetLanguage\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"goog-te-combo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Tiện ích con dịch ngôn ngữ\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"\">Chọn Ngôn ngữ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\tĐược hỗ trợ bởi <span style=\"white-space: nowrap\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"goog-logo-link\" href=\"https://translate.google.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttarget=\"_blank\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_42x16dp.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"37px\" height=\"14px\" style=\"padding-right: 3px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Google Dịch\">Dịch</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-item\" style=\"display: flex; position: absolute;\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\" title=\"VI\" class=\"lang-vi first\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"doGTranslate('vi|vi');return false;\" hreflang=\"vi\"\r\n");
      out.write("\t\t\t\t\t\t\tlang=\"vi\" role=\"menuitem\">VI <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/vn.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"#\" title=\"EN\" class=\"lang-en last\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"doGTranslate('vi|en');return false;\" hreflang=\"en\"\r\n");
      out.write("\t\t\t\t\t\t\tlang=\"en\" role=\"menuitem\"> EN <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/usa.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"img-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"user-login\"><a> <i class=\"flaticon-people\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f3_reused = false;
      try {
        _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f3.setParent(null);
        // /WEB-INF/views/home/header.jsp(212,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
        if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/signup\">Đăng kí</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/login\">Đăng nhập</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
        _jspx_th_c_005fif_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f4_reused = false;
      try {
        _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f4.setParent(null);
        // /WEB-INF/views/home/header.jsp(226,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
        if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<p style=\"color: red\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/my_account?email=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Thông\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttin tài khoản</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-sign-in-alt\"></i> <a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
            out.print(request.getContextPath());
            out.write("/j_spring_security_logout\">Đăng\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\txuất</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f5_reused = false;
            try {
              _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
              // /WEB-INF/views/home/header.jsp(242,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.level == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
              if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"user-item\">\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"sign-in\">\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user-plus\"></i> <a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/admin\">Admin</a>\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
              _jspx_th_c_005fif_005f5_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
        _jspx_th_c_005fif_005f4_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"shoping-cart\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/shopping_cart\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"flaticon-shop\"><span style=\"color: white-space:;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--Header Area End-->\r\n");
      out.write("\t<!-- Mobile Menu Start -->\r\n");
      out.write("\t<div class=\"mobile-menu-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mobile-menu\">\r\n");
      out.write("\t\t\t\t\t\t<nav id=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\">Sách</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\">Khuyến\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmãi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Liên Hệ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Mobile Menu End -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Xử lý ngôn ngữ -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction googleTranslateElementInit2() {\r\n");
      out.write("\t\t\tnew google.translate.TranslateElement({\r\n");
      out.write("\t\t\t\tpageLanguage : 'vi',\r\n");
      out.write("\t\t\t\tautoDisplay : false\r\n");
      out.write("\t\t\t}, 'google_translate_element2');\r\n");
      out.write("\t\t\tvar removePopup = document.getElementById('goog-gt-tt');\r\n");
      out.write("\t\t\tremovePopup.parentNode.removeChild(removePopup);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction GTranslateFireEvent(element, event) {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tif (document.createEventObject) {\r\n");
      out.write("\t\t\t\t\tvar evt = document.createEventObject();\r\n");
      out.write("\t\t\t\t\telement.fireEvent('on' + event, evt)\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar evt = document.createEvent('HTMLEvents');\r\n");
      out.write("\t\t\t\t\tevt.initEvent(event, true, true);\r\n");
      out.write("\t\t\t\t\telement.dispatchEvent(evt)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction doGTranslate(lang_pair) {\r\n");
      out.write("\t\t\tif (lang_pair.value)\r\n");
      out.write("\t\t\t\tlang_pair = lang_pair.value;\r\n");
      out.write("\t\t\tif (lang_pair == '')\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tvar lang = lang_pair.split('|')[1];\r\n");
      out.write("\t\t\tvar teCombo;\r\n");
      out.write("\t\t\tvar sel = document.getElementsByTagName('select');\r\n");
      out.write("\t\t\tfor (var i = 0; sel.length > i; i++) {\r\n");
      out.write("\t\t\t\tif (sel[i].className == 'goog-te-combo')\r\n");
      out.write("\t\t\t\t\tteCombo = sel[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (document.getElementById('google_translate_element2') == null\r\n");
      out.write("\t\t\t\t\t|| document.getElementById('google_translate_element2').innerHTML.length == 0\r\n");
      out.write("\t\t\t\t\t|| teCombo.length == 0 || teCombo.innerHTML.length == 0) {\r\n");
      out.write("\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\tdoGTranslate(lang_pair)\r\n");
      out.write("\t\t\t\t}, 500)\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tteCombo.value = lang;\r\n");
      out.write("\t\t\t\tGTranslateFireEvent(teCombo, 'change');\r\n");
      out.write("\t\t\t\tGTranslateFireEvent(teCombo, 'change')\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<!-- / header section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h2 style=\"color: red;\">ĐẶT HÀNG THÀNH CÔNG</h2>\r\n");
      out.write("\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/shop\"><button>Tiếp\r\n");
      out.write("\t\t\ttục mua hàng</button></a>\r\n");
      out.write("\r\n");
      out.write("\t<!--FOOTER -->\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Footer Area Start -->\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-top-area\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/BookStore\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo-2.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Sứ mệnh của chúng tôi là mang đến cho khách hàng tận hưởng\r\n");
      out.write("\t\t\t\t\t\t\t\tcác dịch vụ chất lượng và nhận được những cuốn sách tốt nhất.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-location\"></i> Q.Thủ Đức, Tp.Hồ Chí\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMinh</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-technology\"></i> (+800) 123 4567 890\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"flaticon-web\"></i> info@bookstore.com</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">VỀ WRITER</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"about.jsp\">Giới thiệu Writer</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Thông tin giao hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Điều khoản sử dụng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Hướng dẫn mua hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">TÀI KHOẢN</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/my_account\">Tài\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tkhoản của tôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login\">Đăng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tnhập</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/shopping_cart\">Giỏ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/wishlist\">Theo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdõi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/checkout\">Thanh\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttoán</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 hidden-sm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">CỬA HÀNG</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách đổi trả hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chương trình thành viên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách mua sĩ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chi nhánh</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Tuyển dụng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer footer-newsletter\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">BẢN TIN WITTER</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hàng ngàn sản phẩm và chương trình khuyến mãi siêu hấp dẫn\r\n");
      out.write("\t\t\t\t\t\t\t\tđang chờ bạn.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Địa chỉ email của bạn ...\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-search btn-small\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tĐĂNG KÍ</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"flaticon-networking\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"social-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-social\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-social-1\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-social-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"flaticon-video\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4 visible-sm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"footer-title\">CỬA HÀNG</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"footer-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách đổi trả hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chương trình thành viên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chính sách mua sĩ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Chi nhánh</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Tuyển dụng</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-bottom\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bottom-left pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tCopyright &copy; 2016 <span><a href=\"#\">DevItems</a></span>. All\r\n");
      out.write("\t\t\t\t\t\t\t\tRight Reserved.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-bottom-right pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/paypal.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- Footer Area End -->\r\n");
      out.write("\r\n");
      out.write("\t<!--Quickview Product Start -->\r\n");
      out.write("\t<div id=\"quickview-wrapper\">\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"productModal1\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-product\" style=\"display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-images\" style=\"width: 60%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"main-image images\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/shop/tn2.jpeg\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1 style=\"font-size: 22px;\">Book Name</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"price-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"s-price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"special-price\"> <span class=\"amount\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 25px;\">500.000đ</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"see-all\">Xem chi tiết</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"quick-add-to-cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display: flex; justify-content: center; align-items: center;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"single_add_to_cart_button\" href=\"#\">Mua Ngay</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"height: 300px; overflow-y: scroll;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"quick-desc\">Hay cực</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- .product-info -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--End of Quickview Product-->\r\n");
      out.write("\t<!-- all js here -->\r\n");
      out.write("\t<!-- jquery latest version -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/vendor/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("\t<!-- bootstrap js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- owl.carousel js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- jquery-ui js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- jquery Counterup js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- jquery countdown js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("\t<!-- jquery countdown js -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/venobox/venobox.min.js\"></script>\r\n");
      out.write("\t<!-- jquery Meanmenu js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.meanmenu.js\"></script>\r\n");
      out.write("\t<!-- wow js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/wow.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tnew WOW().init();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- scrollUp JS -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("\t<!-- plugins js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/plugins.js\"></script>\r\n");
      out.write("\t<!-- Nivo slider js -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/js/jquery.nivo.slider.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/lib/home.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<!-- main js -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/ajax.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- END FOOTER -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/home/header.jsp(256,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.myCartNum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
